module.exports = {
  testEnvironment: "node",
  coverageDirectory: "coverage",
  collectCoverageFrom: ["src/**/*.js", "!src/**/*.test.js"],
  testMatch: ["**/tests/**/*.test.js"],
  setupFilesAfterEnv: ["<rootDir>/tests/setup.js"],
  verbose: true,
  testTimeout: 30000,
  maxWorkers: 1,
  reporters: [
    "default",
    [
      "jest-html-reporter",
      {
        pageTitle: "API E2E Test Report",
        outputPath: "./reports/test-report.html",
        includeFailureMsg: true,
        includeConsoleLog: true,
        theme: "darkTheme",
        logo: "",
        executionTimeWarningThreshold: 5,
        dateFormat: "yyyy-mm-dd HH:MM:ss",
        sort: "status",
        includeObsoleteSnapshots: true,
        customScriptPath: "./reports/custom-report-script.js",
        styleOverridePath: "./reports/custom-report-style.css",
      },
    ],
    [
      "jest-html-reporters",
      {
        publicPath: "./reports/html-report",
        filename: "detailed-report.html",
        pageTitle: "API E2E Detailed Test Report",
        expand: true,
        openReport: false,
        hideIcon: false,
        inlineSource: true,
        urlForTestFiles: "",
        enableMergeData: true,
        dataMergeLevel: 1,
      },
    ],
  ],
};
