const fs = require("fs");
const path = require("path");

/**
 * Enhanced HTML Report Generator
 * Generates a comprehensive, interactive HTML report from Jest test results
 */
class ReportGenerator {
  constructor() {
    this.reportsDir = path.join(__dirname, "../../reports");
    this.testResultsPath = path.join(this.reportsDir, "test-results.json");
    this.outputPath = path.join(this.reportsDir, "enhanced-report.html");
  }

  generateReport() {
    try {
      // Ensure reports directory exists
      if (!fs.existsSync(this.reportsDir)) {
        fs.mkdirSync(this.reportsDir, { recursive: true });
      }

      // Read test results if available
      let testResults = null;
      if (fs.existsSync(this.testResultsPath)) {
        const resultsData = fs.readFileSync(this.testResultsPath, "utf8");
        testResults = JSON.parse(resultsData);
      }

      // Generate HTML
      const html = this.generateHTML(testResults);

      // Write to file
      fs.writeFileSync(this.outputPath, html);

      console.log(`\n✓ Enhanced HTML report generated: ${this.outputPath}\n`);
    } catch (error) {
      console.error("Error generating report:", error.message);
    }
  }

  generateHTML(testResults) {
    const stats = this.calculateStatistics(testResults);
    const timestamp = new Date().toLocaleString();

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API E2E Test Report - Enhanced</title>
    <style>
        ${this.getStyles()}
    </style>
</head>
<body>
    <div class="report-container">
        <!-- Header -->
        <div class="header">
            <h1>🚀 API E2E Test Report</h1>
            <div class="timestamp">Generated on: ${timestamp}</div>
            <div class="environment">Environment: ${process.env.TEST_ENV || "default"} | Base URL: ${process.env.BASE_URL || "N/A"}</div>
        </div>

        <!-- Summary Cards -->
        <div class="summary-cards">
            <div class="summary-card total">
                <div class="label">Total Tests</div>
                <div class="value">${stats.total}</div>
            </div>
            <div class="summary-card passed">
                <div class="label">Passed</div>
                <div class="value">${stats.passed}</div>
            </div>
            <div class="summary-card failed">
                <div class="label">Failed</div>
                <div class="value">${stats.failed}</div>
            </div>
            <div class="summary-card pending">
                <div class="label">Pass Rate</div>
                <div class="value">${stats.passRate}%</div>
            </div>
        </div>

        <!-- Progress Bar -->
        <div class="chart-container">
            <h3>Test Execution Overview</h3>
            <div class="progress-bar">
                <div class="progress-fill" style="width: ${stats.passRate}%">
                    ${stats.passRate}% Pass Rate
                </div>
            </div>
            <div class="stats-grid">
                <div class="stat-item">
                    <div class="stat-value">${stats.duration}s</div>
                    <div class="stat-label">Total Duration</div>
                </div>
                <div class="stat-item">
                    <div class="stat-value">${stats.suites}</div>
                    <div class="stat-label">Test Suites</div>
                </div>
                <div class="stat-item">
                    <div class="stat-value">${stats.avgDuration}ms</div>
                    <div class="stat-label">Avg Test Time</div>
                </div>
            </div>
        </div>

        <!-- Export Button -->
        <div style="text-align: right; margin-bottom: 20px;">
            <button class="export-btn" onclick="exportReport()">📥 Export Results (JSON)</button>
        </div>

        <!-- Search and Filter -->
        <div class="search-container">
            <input 
                type="text" 
                id="testSearch" 
                placeholder="🔍 Search tests..." 
                oninput="searchTests(this.value)"
            />
        </div>

        <div class="filter-buttons">
            <button class="filter-btn all active" onclick="filterTests('all')">All Tests</button>
            <button class="filter-btn passed" onclick="filterTests('passed')">✓ Passed</button>
            <button class="filter-btn failed" onclick="filterTests('failed')">✗ Failed</button>
        </div>

        <!-- Test Suites -->
        ${this.generateTestSuites(testResults)}

        <!-- Footer -->
        <div class="footer">
            <p>Generated by API E2E Testing Framework | Powered by Jest & Axios</p>
            <p>Keyboard shortcuts: Ctrl/Cmd+F to search | ESC to clear search</p>
        </div>
    </div>

    <script>
        ${this.getScripts()}
    </script>
</body>
</html>`;
  }

  calculateStatistics(testResults) {
    if (!testResults) {
      return {
        total: 0,
        passed: 0,
        failed: 0,
        passRate: 0,
        duration: 0,
        suites: 0,
        avgDuration: 0,
      };
    }

    const stats = {
      total: testResults.numTotalTests || 0,
      passed: testResults.numPassedTests || 0,
      failed: testResults.numFailedTests || 0,
      suites: testResults.numTotalTestSuites || 0,
      duration:
        (
          (testResults.testResults?.[0]?.endTime -
            testResults.testResults?.[0]?.startTime) /
          1000
        ).toFixed(2) || 0,
    };

    stats.passRate =
      stats.total > 0 ? ((stats.passed / stats.total) * 100).toFixed(1) : 0;
    stats.avgDuration =
      stats.total > 0 ? ((stats.duration * 1000) / stats.total).toFixed(0) : 0;

    return stats;
  }

  generateTestSuites(testResults) {
    if (!testResults || !testResults.testResults) {
      return '<div class="empty-state">No test results available. Run tests to generate a report.</div>';
    }

    return testResults.testResults
      .map((suite, index) => {
        const suitePassed = suite.numPassingTests || 0;
        const suiteFailed = suite.numFailingTests || 0;
        const suiteTotal = suitePassed + suiteFailed;

        return `
        <div class="test-suite">
            <div class="test-suite-header" onclick="toggleSuite(${index})">
                <div class="test-suite-title">
                    📄 ${this.getSuiteName(suite.testFilePath)}
                </div>
                <div class="test-suite-stats">
                    <span class="stat-badge passed">${suitePassed} passed</span>
                    ${suiteFailed > 0 ? `<span class="stat-badge failed">${suiteFailed} failed</span>` : ""}
                    <span class="stat-badge total">${suiteTotal} total</span>
                </div>
            </div>
            <div class="test-suite-content" id="suite-${index}">
                ${this.generateTestCases(suite.assertionResults)}
            </div>
        </div>
      `;
      })
      .join("");
  }

  generateTestCases(assertionResults) {
    if (!assertionResults || assertionResults.length === 0) {
      return '<div class="test-case">No test cases found</div>';
    }

    return assertionResults
      .map((test) => {
        const status = test.status === "passed" ? "passed" : "failed";
        const duration = test.duration ? `${test.duration}ms` : "N/A";

        return `
        <div class="test-case ${status}">
            <div class="test-name">
                <span class="test-status-icon ${status}"></span>
                <span>${test.title}</span>
            </div>
            <div class="test-duration">${duration}</div>
            ${
              test.failureMessages && test.failureMessages.length > 0
                ? `
                <div class="error-details">${this.escapeHtml(test.failureMessages.join("\n"))}</div>
            `
                : ""
            }
        </div>
      `;
      })
      .join("");
  }

  getSuiteName(filePath) {
    return path.basename(filePath);
  }

  escapeHtml(text) {
    const map = {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#039;",
    };
    return text.replace(/[&<>"']/g, (m) => map[m]);
  }

  getStyles() {
    const cssPath = path.join(
      __dirname,
      "../../reports/custom-report-style.css",
    );
    if (fs.existsSync(cssPath)) {
      return fs.readFileSync(cssPath, "utf8");
    }
    return this.getDefaultStyles();
  }

  getDefaultStyles() {
    return `
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { font-family: 'Segoe UI', sans-serif; background: #f5f5f5; }
      .report-container { max-width: 1400px; margin: 0 auto; padding: 20px; }
      .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 8px; margin-bottom: 30px; }
      .header h1 { font-size: 2.5em; margin-bottom: 10px; }
      .timestamp, .environment { opacity: 0.9; font-size: 0.9em; }
      .summary-cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 30px; }
      .summary-card { background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
      .summary-card.passed { border-left: 4px solid #4CAF50; }
      .summary-card.failed { border-left: 4px solid #f44336; }
      .summary-card.total { border-left: 4px solid #2196F3; }
      .summary-card .label { font-size: 0.9em; color: #666; margin-bottom: 10px; }
      .summary-card .value { font-size: 2.5em; font-weight: bold; }
      .chart-container { background: white; padding: 30px; border-radius: 8px; margin-bottom: 30px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
      .progress-bar { width: 100%; height: 30px; background: #e0e0e0; border-radius: 15px; overflow: hidden; margin: 20px 0; }
      .progress-fill { height: 100%; background: #4CAF50; display: flex; align-items: center; justify-content: center; color: white; font-weight: 600; }
      .stats-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-top: 20px; text-align: center; }
      .stat-value { font-size: 2em; font-weight: bold; color: #667eea; }
      .stat-label { color: #666; margin-top: 5px; }
      .export-btn { background: #667eea; color: white; border: none; padding: 12px 24px; border-radius: 8px; cursor: pointer; font-weight: 600; }
      .search-container input { width: 100%; padding: 12px; margin-bottom: 20px; border: 2px solid #e0e0e0; border-radius: 8px; font-size: 1em; }
      .filter-buttons { display: flex; gap: 10px; margin-bottom: 20px; flex-wrap: wrap; }
      .filter-btn { padding: 10px 20px; border: none; border-radius: 8px; cursor: pointer; font-weight: 600; }
      .filter-btn.all { background: #2196F3; color: white; }
      .filter-btn.passed { background: #4CAF50; color: white; }
      .filter-btn.failed { background: #f44336; color: white; }
      .filter-btn.active { box-shadow: 0 4px 8px rgba(0,0,0,0.2); }
      .test-suite { background: white; margin-bottom: 20px; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
      .test-suite-header { padding: 20px; background: #f8f9fa; border-bottom: 1px solid #e0e0e0; cursor: pointer; display: flex; justify-content: space-between; align-items: center; }
      .test-suite-stats { display: flex; gap: 15px; }
      .stat-badge { padding: 5px 12px; border-radius: 20px; font-size: 0.85em; font-weight: 600; }
      .stat-badge.passed { background: #e8f5e9; color: #2e7d32; }
      .stat-badge.failed { background: #ffebee; color: #c62828; }
      .stat-badge.total { background: #e3f2fd; color: #1976d2; }
      .test-case { padding: 15px 20px; border-bottom: 1px solid #f0f0f0; display: flex; justify-content: space-between; align-items: center; }
      .test-case.passed { background: #f1f8f4; }
      .test-case.failed { background: #fff5f5; }
      .test-name { flex: 1; display: flex; align-items: center; gap: 10px; }
      .test-status-icon.passed::before { content: '✓'; color: #4CAF50; }
      .test-status-icon.failed::before { content: '✗'; color: #f44336; }
      .test-duration { color: #666; font-size: 0.9em; }
      .error-details { margin-top: 10px; padding: 15px; background: #fff; border-left: 3px solid #f44336; border-radius: 4px; font-family: monospace; font-size: 0.9em; color: #d32f2f; }
      .footer { text-align: center; margin-top: 40px; padding: 20px; color: #666; }
      .empty-state { text-align: center; padding: 60px 20px; color: #999; font-size: 1.2em; }
    `;
  }

  getScripts() {
    const jsPath = path.join(
      __dirname,
      "../../reports/custom-report-script.js",
    );
    SampleReport / sample - report.html;
    if (fs.existsSync(jsPath)) {
      return fs.readFileSync(jsPath, "utf8");
    }
    return this.getDefaultScripts();
  }

  getDefaultScripts() {
    return `
      function toggleSuite(index) {
        const content = document.getElementById('suite-' + index);
        content.style.display = content.style.display === 'none' ? 'block' : 'none';
      }
      
      function filterTests(type) {
        document.querySelectorAll('.filter-btn').forEach(btn => btn.classList.remove('active'));
        document.querySelector('.filter-btn.' + type).classList.add('active');
        document.querySelectorAll('.test-case').forEach(tc => {
          tc.style.display = type === 'all' || tc.classList.contains(type) ? 'flex' : 'none';
        });
      }
      
      function searchTests(query) {
        const term = query.toLowerCase();
        document.querySelectorAll('.test-case').forEach(tc => {
          const text = tc.textContent.toLowerCase();
          tc.style.display = text.includes(term) ? 'flex' : 'none';
        });
      }
      
      function exportReport() {
        const data = { timestamp: new Date().toISOString(), results: [] };
        document.querySelectorAll('.test-case').forEach(tc => {
          data.results.push({
            name: tc.querySelector('.test-name').textContent.trim(),
            status: tc.classList.contains('passed') ? 'passed' : 'failed'
          });
        });
        const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'test-results-' + Date.now() + '.json';
        a.click();
      }
    `;
  }
}

// Run the generator
if (require.main === module) {
  const generator = new ReportGenerator();
  generator.generateReport();
}

module.exports = ReportGenerator;
